# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: uerma <uerma@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/22 15:11:34 by uerma             #+#    #+#              #
#    Updated: 2020/02/23 18:55:06 by uerma            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_check_00.c ft_check_01.c ft_check_02.c ft_check_03.c ft_check_04.c \
		ft_putchar.c ft_putnbr.c ft_putstr.c main.c

all: colle-2

colle-2: $(SRCS)
	gcc -Wall -Wextra -Werror $(SRCS) -o colle-2

fclean:
	rm -f colle-2
